---
title: "Standard errors of probabilities, RR and RD estimations using a logistic MSM"
author: "Benoît Lepage"
date: "March 21, 2023"
output:
  pdf_document: default
---

# 1) Introduction
The `ltmleMSM` function from the `ltmle` package estimates parameters of a working Marginal Structural Model (MSM). The MSM is a logistic regression from which OR estimates can be easily calculated using the exponential of the estimated coefficients.

Applying delta method, it is possible to estimate relative risks and risk diffenrences from the same logistic regression MSM.

In order to estimate the marginal interaction effect between two binary exposures $A_1$ and $A_2$, the following MSM is applied:
\begin{equation*}
  \text{logit} m_\beta(A_1,A_2) = \ln \frac{P\left(Y_{A_1,A_2}=1 \right)}{P\left(Y_{A_1,A_2}=0 \right)} = \beta_0 +\beta_1 A_1 + \beta_2 A_2 + \beta_3 (A_1 \times A_2)
\end{equation*}

For given values $A_1 = a_1$ and $A_2 = a_2$, we note the predicted probability:
\begin{equation*}
  m_\beta(a_1,a_2) = \frac{\exp\left(\beta_0 +\beta_1 a_1 + \beta_2 a_2 + \beta_3 (a_1 \times a_2)\right)}{1 + \exp\left(\beta_0 +\beta_1 a_1 + \beta_2 a_2 + \beta_3 (a_1 \times a_2)\right)}
\end{equation*}

We also note:
\begin{equation*}
  e_{a_1,a_2} = \exp\left(-\beta_0 -\beta_1 a_1 - \beta_2 a_2 - \beta_3 (a_1 \times a_2)\right)
\end{equation*}
so that:
\begin{equation*}
  m_\beta(a_1,a_2) = \frac{1}{1 + e_{a_1,a_2}}
\end{equation*}

and
\begin{align*}
  P\left( Y_{A_1=0,A_2=0}=1 \right) = m_\beta(0,0) &= \frac{1}{1 + \exp(-\beta_0) } = \frac{1}{1 + e_{00}} \\
  P\left( Y_{A_1=1,A_2=0}=1 \right) = m_\beta(1,0) &= \frac{1}{1+\exp(-\beta_0 - \beta_1)} = \frac{1}{1 + e_{10}} \\
  P\left( Y_{A_1=0,A_2=1}=1 \right) = m_\beta(0,1) &= \frac{1}{1+\exp(-\beta_0 - \beta_2)} = \frac{1}{1 + e_{01}} \\
  P\left( Y_{A_1=1,A_2=1}=1 \right) = m_\beta(1,1) &= \frac{1}{1+\exp(-\beta_0 - \beta_1 - \beta_2 - \beta_3)} = \frac{1}{1 + e_{11}} 
\end{align*}

For a given function $f(\beta)$ of the $\beta = \{\beta_0,\beta_1,\beta_2,\beta_3\}$ coefficients such as $m_\beta(a_1,a_2)$, by Delta method, the variance of $f(\beta)$ can be calculed by:
\begin{equation*}
  var\left[f(\beta)\right]=\left( \frac{\partial f(\beta)}{\partial \beta} \right)^T var(\beta) \left( \frac{\partial f(\beta)}{\partial \beta} \right)
\end{equation*}
where $var(\beta)$ is a $4 \times 4$ covariance matrix, that can be estimated using the variance of the influence curve (`IC`) of the MSM coefficients given in the output values of the `ltmleMSM` function, divided by the sample size: `var(IC) / n`.


<!-- ######################################################################## -->
# 2) Standard errors of point estimates of the probabilities of interest
## 2.1) Standard error of $P\left( Y_{A_1=0,A_2=0}=1\right) = m_\beta(0,0)$
\begin{equation*}
  m_\beta(0,0) = \frac{1}{1+ e_{00}} \text{, where } e_{00} = \exp(-\beta_0) 
\end{equation*}

The partial derivative of $f(\beta)=m_\beta(0,0)$ with respect to $\beta$ is:
\begin{equation*}
  \left( \frac{\partial m_\beta(0,0)}{\partial \beta} \right) = \frac{-\left(\frac{\partial e_{00}}{\partial \beta}\right)}{(1+e_{00})^2}
\end{equation*}

where $\left(\frac{\partial e_{00}}{\partial \beta_0} \right) = - e_{00}$ and $\left(\frac{\partial e_{00}}{\partial \beta_1} \right) = \left(\frac{\partial e_{00}}{\partial \beta_2} \right) = \left(\frac{\partial e_{00}}{\partial \beta_3} \right) = 0$.

\begin{align*}
  \left( \frac{\partial m_\beta(0,0)}{\partial \beta_0}\right) &= \frac{-(-e_{00})}{(1+e_{00})^2}= \frac{1+e_{00}-1}{(1+e_{00})} \times \frac{1}{1+e_{00}} \\
                                                            &= \left[1-m_\beta(0,0)\right] \times m_\beta(0,0)
\end{align*}

\begin{equation*}
  \left( \frac{\partial m_\beta(0,0)}{\partial \beta} \right) = \begin{pmatrix} 
    \left( \frac{\partial m_\beta(0,0)}{\partial \beta_0} \right) \\
    \left( \frac{\partial m_\beta(0,0)}{\partial \beta_1} \right) \\
    \left( \frac{\partial m_\beta(0,0)}{\partial \beta_2} \right) \\
    \left( \frac{\partial m_\beta(0,0)}{\partial \beta_3} \right) \end{pmatrix} = \begin{pmatrix}
        \left[1 - m_\beta(0,0) \right] \times m_\beta(0,0) \\
        \frac{-0}{(1+e_{00})^2} \\
        \frac{-0}{(1+e_{00})^2} \\
        \frac{-0}{(1+e_{00})^2} \end{pmatrix} = \begin{pmatrix}
                                                    \left[1 - m_\beta(0,0) \right] \times m_\beta(0,0) \\
                                                    0 \\
                                                    0 \\
                                                    0 \end{pmatrix}
\end{equation*}

The variance of $m_\beta(0,0)$ can then be calculated by:
\begin{equation*}
  var\left( m_\beta(0,0)\right) = \begin{pmatrix} \left[1 - m_\beta(0,0) \right] \times m_\beta(0,0) \\ 0 \\ 0 \\ 0 \end{pmatrix}^T \times \frac{var(IC)}{n} \times \begin{pmatrix}
          \left[1 - m_\beta(0,0) \right] \times m_\beta(0,0) \\
          0 \\
          0 \\
          0 \end{pmatrix}
\end{equation*}

<!-- ######################################################################## -->
\newpage
## 2.2) Standard error of $P\left( Y_{A_1=1,A_2=0}=1 \right) = m_\beta(1,0)$
\begin{equation*}
  m_\beta(1,0) = \frac{1}{1+ e_{10}} \text{, where } e_{10} = \exp(-\beta_0 - \beta_1) 
\end{equation*}

The partial derivative of $f(\beta)=m_\beta(1,0)$ with respect to $\beta$ is:
\begin{equation*}
  \left( \frac{\partial m_\beta(1,0)}{\partial \beta} \right) = \frac{-\left(\frac{\partial e_{10}}{\partial \beta}\right)}{(1+e_{10})^2}
\end{equation*}

where $\left(\frac{\partial e_{10}}{\partial \beta_0} \right) = \left(\frac{\partial e_{10}}{\partial \beta_1} \right) = - e_{10}$ and $\left(\frac{\partial e_{10}}{\partial \beta_2} \right) = \left(\frac{\partial e_{10}}{\partial \beta_3} \right) = 0$.

\begin{align*}
  \left( \frac{\partial m_\beta(1,0)}{\partial \beta_0}\right) = \left( \frac{\partial m_\beta(1,0)}{\partial \beta_1}\right) &= \frac{-(-e_{10})}{(1+e_{10})^2}= \frac{1+e_{10}-1}{(1+e_{10})} \times \frac{1}{1+e_{10}} \\
                                                            &= \left[1-m_\beta(1,0)\right] \times m_\beta(1,0)
\end{align*}


\begin{equation*}
  \left( \frac{\partial m_\beta(1,0)}{\partial \beta} \right) = \begin{pmatrix}
    \left[1 - m_\beta(1,0) \right] \times m_\beta(1,0) \\
    \left[1 - m_\beta(1,0) \right] \times m_\beta(1,0) \\
    \frac{-0}{(1+e_{10})^2} \\
    \frac{-0}{(1+e_{10})^2} \end{pmatrix} = \begin{pmatrix}
                                                \left[1 - m_\beta(1,0) \right] \times m_\beta(1,0) \\
                                                \left[1 - m_\beta(1,0) \right] \times m_\beta(1,0) \\
                                                0 \\
                                                0 \end{pmatrix}
\end{equation*}

The variance of $m_\beta(1,0)$ can then be calculated by:
\begin{equation*}
  var\left( m_\beta(1,0)\right) = \begin{pmatrix} 
      \left[1 - m_\beta(1,0) \right] \times m_\beta(1,0) \\ 
      \left[1 - m_\beta(1,0) \right] \times m_\beta(1,0) \\ 
      0 \\ 
      0 \end{pmatrix}^T \times \frac{var(IC)}{n} \times \begin{pmatrix}
          \left[1 - m_\beta(1,0) \right] \times m_\beta(1,0) \\
          \left[1 - m_\beta(1,0) \right] \times m_\beta(1,0) \\
          0 \\
          0 \end{pmatrix}
\end{equation*}


<!-- ######################################################################## -->
\newpage
## 2.3) Standard error of $P\left( Y_{A_1=0,A_2=1}=1 \right) = m_\beta(0,1)$
\begin{equation*}
  m_\beta(0,1) = \frac{1}{1+ e_{01}} \text{, where } e_{01} = \exp(-\beta_0 - \beta_2) 
\end{equation*}

The partial derivative of $f(\beta)=m_\beta(0,1)$ with respect to $\beta$ is:
\begin{equation*}
  \left( \frac{\partial m_\beta(0,1)}{\partial \beta} \right) = \frac{-\left(\frac{\partial e_{01}}{\partial \beta}\right)}{(1+e_{01})^2}
\end{equation*}

where $\left(\frac{\partial e_{01}}{\partial \beta_0} \right) = \left(\frac{\partial e_{01}}{\partial \beta_2} \right) = - e_{01}$ and $\left(\frac{\partial e_{01}}{\partial \beta_1} \right) = \left(\frac{\partial e_{01}}{\partial \beta_3} \right) = 0$.

\begin{align*}
  \left( \frac{\partial m_\beta(0,1)}{\partial \beta_0}\right) = \left( \frac{\partial m_\beta(0,1)}{\partial \beta_2}\right) &= \frac{-(-e_{01})}{(1+e_{01})^2}= \frac{1+e_{01}-1}{(1+e_{01})} \times \frac{1}{1+e_{01}} \\
                                                            &= \left[1-m_\beta(0,1)\right] \times m_\beta(0,1)
\end{align*}

\begin{equation*}
  \left( \frac{\partial m_\beta(0,1)}{\partial \beta} \right) = \begin{pmatrix}
    \left[1 - m_\beta(0,1) \right] \times m_\beta(0,1) \\
    \frac{-0}{(1+e_{01})^2} \\
    \left[1 - m_\beta(0,1) \right] \times m_\beta(0,1) \\
    \frac{-0}{(1+e_{01})^2} \end{pmatrix} = \begin{pmatrix}
                                                \left[1 - m_\beta(0,1) \right] \times m_\beta(0,1) \\
                                                0 \\
                                                \left[1 - m_\beta(0,1) \right] \times m_\beta(0,1) \\
                                                0 \end{pmatrix}
\end{equation*}

The variance of $m_\beta(0,1)$ can then be calculated by:
\begin{equation*}
  var\left( m_\beta(0,1)\right) = \begin{pmatrix} 
      \left[1 - m_\beta(0,1) \right] \times m_\beta(0,1) \\ 
      0 \\ 
      \left[1 - m_\beta(0,1) \right] \times m_\beta(0,1) \\ 
      0 \end{pmatrix}^T \times \frac{var(IC)}{n} \times \begin{pmatrix}
          \left[1 - m_\beta(0,1) \right] \times m_\beta(0,1) \\
          0 \\
          \left[1 - m_\beta(0,1) \right] \times m_\beta(0,1) \\
          0 \end{pmatrix}
\end{equation*}

<!-- ######################################################################## -->
\newpage
## 2.4) Standard error of $P\left( Y_{A_1=1,A_2=1}=1 \right) = m_\beta(1,1)$
\begin{equation*}
  m_\beta(1,1) = \frac{1}{1+ e_{11}} \text{, where } e_{11} = \exp(-\beta_0 - \beta_1 - \beta_2 - \beta_3) 
\end{equation*}

The partial derivative of $f(\beta)=m_\beta(1,1)$ with respect to $\beta$ is:
\begin{equation*}
  \left( \frac{\partial m_\beta(1,1)}{\partial \beta} \right) = \frac{-\left(\frac{\partial e_{11}}{\partial \beta}\right)}{(1+e_{11})^2}
\end{equation*}

where $\left(\frac{\partial e_{11}}{\partial \beta_0} \right) = \left(\frac{\partial e_{11}}{\partial \beta_2} \right) = \left(\frac{\partial e_{11}}{\partial \beta_1} \right) = \left(\frac{\partial e_{11}}{\partial \beta_3} \right) = - e_{11}$.

\begin{align*}
  \left( \frac{\partial m_\beta(1,1)}{\partial \beta_0}\right) = \left( \frac{\partial m_\beta(1,1)}{\partial \beta_1}\right) = \left( \frac{\partial m_\beta(1,1)}{\partial \beta_2}\right) = \left( \frac{\partial m_\beta(1,1)}{\partial \beta_3}\right) &= \frac{-(-e_{11})}{(1+e_{11})^2}= \frac{1+e_{11}-1}{(1+e_{11})} \times \frac{1}{1+e_{11}} \\
                                                            &= \left[1-m_\beta(1,1)\right] \times m_\beta(1,1)
\end{align*}

\begin{equation*}
  \left( \frac{\partial m_\beta(1,1)}{\partial \beta} \right) = \begin{pmatrix}
        \left[1 - m_\beta(1,1) \right] \times m_\beta(1,1) \\
        \left[1 - m_\beta(1,1) \right] \times m_\beta(1,1) \\
        \left[1 - m_\beta(1,1) \right] \times m_\beta(1,1) \\
        \left[1 - m_\beta(1,1) \right] \times m_\beta(1,1) \end{pmatrix}
\end{equation*}

The variance of $m_\beta(1,1)$ can then be calculated by:
\begin{equation*}
  var\left( m_\beta(1,1)\right) = \begin{pmatrix} 
      \left[1 - m_\beta(1,1) \right] \times m_\beta(1,1) \\ 
      \left[1 - m_\beta(1,1) \right] \times m_\beta(1,1) \\ 
      \left[1 - m_\beta(1,1) \right] \times m_\beta(1,1) \\ 
      \left[1 - m_\beta(1,1) \right] \times m_\beta(1,1) \end{pmatrix}^T \times \frac{var(IC)}{n} \times \begin{pmatrix}
          \left[1 - m_\beta(1,1) \right] \times m_\beta(1,1) \\
          \left[1 - m_\beta(1,1) \right] \times m_\beta(1,1) \\
          \left[1 - m_\beta(1,1) \right] \times m_\beta(1,1) \\
          \left[1 - m_\beta(1,1) \right] \times m_\beta(1,1) \end{pmatrix}
\end{equation*}

<!-- ######################################################################## -->
\newpage
# 3) Standard errors of risk differences
## 3.1) Risk difference for the effect of $A_1$, setting $A_2=0$

\begin{equation*}
  RD_{A_1 \mid A_2 = 0} = m_\beta(1,0) - m_\beta(0,0) = \frac{1}{1 + e_{10}} - \frac{1}{1 + e_{00}}
\end{equation*}
where $e_{00} = \exp(-\beta_0)$ and $e_{10} = \exp(-\beta_0 - \beta_1)$.

The partial derivative of the risk difference $m_\beta(1,0) - m_\beta(0,0)$ with respect to $\beta$ is:
\begin{equation*}
   \frac{\partial }{\partial \beta} \left(m_\beta(1,0) - m_\beta(0,0) \right) = \frac{-\left(\frac{\partial e_{10}}{\partial \beta}\right)}{(1+e_{10})^2} - \frac{-\left(\frac{\partial e_{00}}{\partial \beta}\right)}{(1+e_{00})^2}
\end{equation*}

\begin{align*}
   \frac{\partial }{\partial \beta_0} \left(m_\beta(1,0) - m_\beta(0,0) \right) &= \frac{-(-e_{10})}{(1+e_{10})^2} - \frac{-(-e_{00})}{(1+e_{00})^2} \\
     &= [1 - m_\beta(1,0)] \times m_\beta(1,0) - [1 - m_\beta(0,0)] \times m_\beta(0,0)
\end{align*}

\begin{equation*}
   \frac{\partial }{\partial \beta_1} \left(m_\beta(1,0) - m_\beta(0,0) \right) = \frac{-(-e_{10})}{(1+e_{10})^2} - 0 =  [1 - m_\beta(1,0)] \times m_\beta(1,0) 
\end{equation*}

\begin{equation*}
  \text{and } \frac{\partial }{\partial \beta_2} \left(m_\beta(1,0) - m_\beta(0,0) \right) =
   \frac{\partial }{\partial \beta_3} \left(m_\beta(1,0) - m_\beta(0,0) \right) = 0
\end{equation*}

\begin{equation*}
  \frac{\partial }{\partial \beta} \left( m_\beta(1,0) - m_\beta(0,0) \right) = \begin{pmatrix}
        [1 - m_\beta(1,0)] \times m_\beta(1,0) - [1 - m_\beta(0,0)] \times m_\beta(0,0) \\
        [1 - m_\beta(1,0)] \times m_\beta(1,0)  \\
        0 \\
        0 \end{pmatrix} = \Delta
\end{equation*}

The variance of $RD_{A_1 \mid A_2 = 0}$ can then be calculated by:
\begin{equation*}
  var\left( RD_{A_1 \mid A_2 = 0}\right) = \Delta^T \times \frac{var(IC)}{n} \times \Delta
\end{equation*}



<!-- ######################################################################## -->
\newpage
## 3.2) Risk difference for the effect of $A_1$, setting $A_2=1$

\begin{equation*}
  RD_{A_1 \mid A_2 = 1} = m_\beta(1,1) - m_\beta(0,1) = \frac{1}{1 + e_{11}} - \frac{1}{1 + e_{01}}
\end{equation*}
where $e_{11} = \exp(-\beta_0 - \beta_1 - \beta_2 - \beta_3)$ and $e_{01} = \exp(-\beta_0 - \beta_2)$.

The partial derivative of the risk difference $m_\beta(1,1) - m_\beta(0,1)$ with respect to $\beta$ is:
\begin{equation*}
   \frac{\partial }{\partial \beta} \left(m_\beta(1,1) - m_\beta(0,1) \right) = \frac{-\left(\frac{\partial e_{11}}{\partial \beta}\right)}{(1+e_{11})^2} - \frac{-\left(\frac{\partial e_{01}}{\partial \beta}\right)}{(1+e_{01})^2}
\end{equation*}

\begin{align*}
   \frac{\partial }{\partial \beta_0} \left(m_\beta(1,1) - m_\beta(0,1) \right) &= \frac{-(-e_{11})}{(1+e_{11})^2} - \frac{-(-e_{01})}{(1+e_{01})^2} \\
     &= [1 - m_\beta(1,1)] \times m_\beta(1,1) - [1 - m_\beta(0,1)] \times m_\beta(0,1)
\end{align*}

\begin{equation*}
   \frac{\partial }{\partial \beta_1} \left(m_\beta(1,1) - m_\beta(0,1) \right) = \frac{-(-e_{11})}{(1+e_{11})^2} - 0 =  [1 - m_\beta(1,1)] \times m_\beta(1,1) 
\end{equation*}

\begin{align*}
   \frac{\partial }{\partial \beta_2} \left(m_\beta(1,1) - m_\beta(0,1) \right) &= \frac{-(-e_{11})}{(1+e_{11})^2} - \frac{-(-e_{01})}{(1+e_{01})^2} \\
     &= [1 - m_\beta(1,1)] \times m_\beta(1,1) - [1 - m_\beta(0,1)] \times m_\beta(0,1)
\end{align*}

\begin{equation*}
   \frac{\partial }{\partial \beta_3} \left(m_\beta(1,1) - m_\beta(0,1) \right) = \frac{-(-e_{11})}{(1+e_{11})^2} - 0 =  [1 - m_\beta(1,1)] \times m_\beta(1,1) 
\end{equation*}

\begin{equation*}
  \frac{\partial }{\partial \beta} \left( m_\beta(1,1) - m_\beta(0,1) \right) = \begin{pmatrix}
        [1 - m_\beta(1,1)] \times m_\beta(1,1) - [1 - m_\beta(0,1)] \times m_\beta(0,1) \\
        [1 - m_\beta(1,1)] \times m_\beta(1,1)  \\
        [1 - m_\beta(1,1)] \times m_\beta(1,1) - [1 - m_\beta(0,1)] \times m_\beta(0,1) \\
        [1 - m_\beta(1,1)] \times m_\beta(1,1) \end{pmatrix} = \Delta
\end{equation*}

The variance of $RD_{A_1 \mid A_2 = 1}$ can then be calculated by:
\begin{equation*}
  var\left( RD_{A_1 \mid A_2 = 0}\right) = \Delta^T \times \frac{var(IC)}{n} \times \Delta
\end{equation*}


<!-- ######################################################################## -->
\newpage
## 3.3) Risk difference for the effect of $A_2$, setting $A_1=0$

\begin{equation*}
  RD_{A_2 \mid A_1 = 0} = m_\beta(0,1) - m_\beta(0,0) = \frac{1}{1 + e_{01}} - \frac{1}{1 + e_{00}}
\end{equation*}
where $e_{01} = \exp(-\beta_0 - \beta_2)$ and $e_{00} = \exp(-\beta_0)$.

The partial derivative of the risk difference $m_\beta(0,1) - m_\beta(0,0)$ with respect to $\beta$ is:
\begin{equation*}
   \frac{\partial }{\partial \beta} \left(m_\beta(0,1) - m_\beta(0,0) \right) = \frac{-\left(\frac{\partial e_{01}}{\partial \beta}\right)}{(1+e_{01})^2} - \frac{-\left(\frac{\partial e_{00}}{\partial \beta}\right)}{(1+e_{00})^2}
\end{equation*}

\begin{align*}
   \frac{\partial }{\partial \beta_0} \left(m_\beta(0,1) - m_\beta(0,0) \right) &= \frac{-(-e_{01})}{(1+e_{01})^2} - \frac{-(-e_{00})}{(1+e_{00})^2} \\
     &= [1 - m_\beta(0,1)] \times m_\beta(0,1) - [1 - m_\beta(0,0)] \times m_\beta(0,0)
\end{align*}

\begin{equation*}
   \frac{\partial }{\partial \beta_1} \left(m_\beta(0,1) - m_\beta(0,0) \right) = 0
\end{equation*}

\begin{align*}
   \frac{\partial }{\partial \beta_2} \left(m_\beta(0,1) - m_\beta(0,0) \right) &= \frac{-(-e_{01})}{(1+e_{01})^2} - 0 \\
     &= [1 - m_\beta(0,1)] \times m_\beta(0,1)
\end{align*}

\begin{equation*}
   \frac{\partial }{\partial \beta_3} \left(m_\beta(0,1) - m_\beta(0,0) \right) = 0
\end{equation*}

\begin{equation*}
  \frac{\partial }{\partial \beta} \left( m_\beta(0,1) - m_\beta(0,0) \right) = \begin{pmatrix}
        [1 - m_\beta(0,1)] \times m_\beta(0,1) - [1 - m_\beta(0,0)] \times m_\beta(0,0)  \\
        0  \\
        [1 - m_\beta(0,1)] \times m_\beta(0,1)\\
        0 \end{pmatrix} = \Delta
\end{equation*}

The variance of $RD_{A_2 \mid A_1 = 0}$ can then be calculated by:
\begin{equation*}
  var\left( RD_{A_2 \mid A_1 = 0}\right) = \Delta^T \times \frac{var(IC)}{n} \times \Delta
\end{equation*}


<!-- ######################################################################## -->
\newpage
## 3.4) Risk difference for the effect of $A_2$, setting $A_1=1$

\begin{equation*}
  RD_{A_2 \mid A_1 = 1} = m_\beta(1,1) - m_\beta(1,0) = \frac{1}{1 + e_{11}} - \frac{1}{1 + e_{10}}
\end{equation*}
where $e_{11} = \exp(-\beta_0 - \beta_1 - \beta_2 - \beta_3)$ and $e_{10} = \exp(-\beta_0 - \beta_1)$.

The partial derivative of the risk difference $m_\beta(1,1) - m_\beta(1,0)$ with respect to $\beta$ is:
\begin{equation*}
   \frac{\partial }{\partial \beta} \left(m_\beta(1,1) - m_\beta(1,0) \right) = \frac{-\left(\frac{\partial e_{11}}{\partial \beta}\right)}{(1+e_{11})^2} - \frac{-\left(\frac{\partial e_{10}}{\partial \beta}\right)}{(1+e_{10})^2}
\end{equation*}

\begin{align*}
   \frac{\partial }{\partial \beta_0} \left(m_\beta(1,1) - m_\beta(1,0) \right) &= \frac{-(-e_{11})}{(1+e_{11})^2} - \frac{-(-e_{10})}{(1+e_{10})^2} \\
     &= [1 - m_\beta(1,1)] \times m_\beta(1,1) - [1 - m_\beta(1,0)] \times m_\beta(1,0)
\end{align*}

\begin{align*}
   \frac{\partial }{\partial \beta_1} \left(m_\beta(1,1) - m_\beta(1,0) \right) &= \frac{-(-e_{11})}{(1+e_{11})^2} - \frac{-(-e_{10})}{(1+e_{10})^2} \\
     &= [1 - m_\beta(1,1)] \times m_\beta(1,1) - [1 - m_\beta(1,0)] \times m_\beta(1,0)
\end{align*}

\begin{align*}
   \frac{\partial }{\partial \beta_2} \left(m_\beta(1,1) - m_\beta(1,0) \right) &= \frac{-(-e_{11})}{(1+e_{11})^2} - 0 \\
     &= [1 - m_\beta(1,1)] \times m_\beta(1,1)
\end{align*}

\begin{align*}
   \frac{\partial }{\partial \beta_3} \left(m_\beta(1,1) - m_\beta(1,0) \right) &= \frac{-(-e_{11})}{(1+e_{11})^2} - 0 \\
     &= [1 - m_\beta(1,1)] \times m_\beta(1,1)
\end{align*}

\begin{equation*}
  \frac{\partial }{\partial \beta} \left( m_\beta(1,1) - m_\beta(1,0) \right) = \begin{pmatrix}
        [1 - m_\beta(1,1)] \times m_\beta(1,1) - [1 - m_\beta(1,0)] \times m_\beta(1,0)  \\
        [1 - m_\beta(1,1)] \times m_\beta(1,1) - [1 - m_\beta(1,0)] \times m_\beta(1,0)  \\
        [1 - m_\beta(1,1)] \times m_\beta(1,1)\\
        [1 - m_\beta(1,1)] \times m_\beta(1,1) \end{pmatrix} = \Delta
\end{equation*}

The variance of $RD_{A_2 \mid A_1 = 1}$ can then be calculated by:
\begin{equation*}
  var\left( RD_{A_2 \mid A_1 = 1}\right) = \Delta^T \times \frac{var(IC)}{n} \times \Delta
\end{equation*}


<!-- ######################################################################## -->
\newpage
# 4) Standard errors of relative risks
## 4.1) Relative risk for the effect of $A_1$, setting $A_2=0$
Applying a log transformation of the relative risk,
\begin{equation*}
  \log RR_{A_1 \mid A_2 = 0} = \log \frac{m_\beta(1,0)}{m_\beta(0,0)}  = \log m_\beta(1,0) - \log m_\beta(0,0)
\end{equation*}

and the variance of $\log RR$ is:
\begin{equation*}
  var(\log RR) = \left( \frac{\partial \log RR}{\partial \beta}\right)^T \times var(\beta) \times \left( \frac{\partial \log RR}{\partial \beta}\right)
\end{equation*}

With $m_\beta=\frac{1}{1+e}$, we have: $(\log m_\beta)^\prime = \frac{m_\beta^\prime}{m_\beta} = \frac{-e^\prime}{(1+e)^2} \times (1+e) = \frac{-e^\prime}{1+e}$

where $e_{00} = \exp(-\beta_0)$ and $e_{10} = \exp(-\beta_0 - \beta_1)$.

\begin{align*}
  \frac{\partial \log RR_{A_1 \mid A_2 = 0}}{\partial \beta_0} =& \frac{-(-e_{10})}{1 + e_{10}} - \frac{-(-e_{00})}{1 + e_{00}} \\
  =& \frac{1 + e_{10} - 1}{1 + e_{10}} - \frac{1 + e_{00} - 1}{1 + e_{00}} \\
  =& \left[1- m_\beta(1,0)\right] - \left[1 - m_\beta(0,0)\right] = m_\beta(0,0) - m_\beta(1,0)
\end{align*}

\begin{align*}
  \frac{\partial \log RR_{A_1 \mid A_2 = 0}}{\partial \beta_1} =& \frac{-(-e_{10})}{1 + e_{10}} - 0 \\
  =& \frac{1 + e_{10} - 1}{1 + e_{10}} = 1- m_\beta(1,0)
\end{align*}

\begin{equation*}
  \frac{\partial \log RR_{A_1 \mid A_2 = 0}}{\partial \beta_2} =\frac{\partial \log RR_{A_1 \mid A_2 = 0}}{\partial \beta_3} = 0
\end{equation*}

\begin{equation*}
  \frac{\partial \log RR_{A_1 \mid A_2 = 0}}{\partial \beta} = \begin{pmatrix} 
    m_\beta(0,0) - m_\beta(1,0) \\
    1- m_\beta(1,0) \\
    0 \\
    0
    \end{pmatrix} = \Delta
\end{equation*}

The variance of $\log RR_{A_1 \mid A_2 = 0}$ can then be calculated by:
\begin{equation*}
  var\left( \log RR_{A_1 \mid A_2 = 0}\right) = \Delta^T \times \frac{var(IC)}{n} \times \Delta
\end{equation*}

<!-- ######################################################################## -->
\newpage
## 4.2) Relative risk for the effect of $A_1$, setting $A_2=1$
\begin{equation*}
  \log RR_{A_1 \mid A_2 = 1} = \log \frac{m_\beta(1,1)}{m_\beta(0,1)}  = \log m_\beta(1,1) - \log m_\beta(0,1)
\end{equation*}

With $m_\beta=\frac{1}{1+e}$, we have: $(\log m_\beta)^\prime = \frac{m_\beta^\prime}{m_\beta} = \frac{-e^\prime}{(1+e)^2} \times (1+e) = \frac{-e^\prime}{1+e}$

where $e_{01} = \exp(-\beta_0 - \beta_2)$ and $e_{11} = \exp(-\beta_0 - \beta_1 - \beta_2 -\beta_3)$.

\begin{align*}
  \frac{\partial \log RR_{A_1 \mid A_2 = 1}}{\partial \beta_0} =& \frac{-(-e_{11})}{1 + e_{11}} - \frac{-(-e_{01})}{1 + e_{01}} \\
  =& \frac{1 + e_{11} - 1}{1 + e_{11}} - \frac{1 + e_{01} - 1}{1 + e_{01}} \\
  =& \left[1- m_\beta(1,1)\right] - \left[1 - m_\beta(0,1)\right] = m_\beta(0,1) - m_\beta(1,1)
\end{align*}

\begin{align*}
  \frac{\partial \log RR_{A_1 \mid A_2 = 1}}{\partial \beta_1} =& \frac{-(-e_{11})}{1 + e_{11}} - 0 \\
  =& \frac{1 + e_{11} - 1}{1 + e_{11}} = 1- m_\beta(1,1)
\end{align*}

\begin{equation*}
  \frac{\partial \log RR_{A_1 \mid A_2 = 1}}{\partial \beta_2} = m_\beta(0,1) - m_\beta(1,1)
\end{equation*}

\begin{align*}
  \frac{\partial \log RR_{A_1 \mid A_2 = 1}}{\partial \beta_3} =& \frac{-(-e_{11})}{1 + e_{11}} - 0 \\
  =& \frac{1 + e_{11} - 1}{1 + e_{11}} = 1- m_\beta(1,1)
\end{align*}



\begin{equation*}
  \frac{\partial \log RR_{A_1 \mid A_2 = 1}}{\partial \beta} = \begin{pmatrix} 
    m_\beta(0,1) - m_\beta(1,1) \\
    1- m_\beta(1,1) \\
    m_\beta(0,1) - m_\beta(1,1) \\
    1- m_\beta(1,1)
    \end{pmatrix} = \Delta
\end{equation*}

The variance of $\log RR_{A_1 \mid A_2 = 1}$ can then be calculated by:
\begin{equation*}
  var\left( \log RR_{A_1 \mid A_2 = 1}\right) = \Delta^T \times \frac{var(IC)}{n} \times \Delta
\end{equation*}


<!-- ######################################################################## -->
\newpage
## 4.3) Relative risk for the effect of $A_2$, setting $A_1=0$
\begin{equation*}
  \log RR_{A_2 \mid A_1 = 0} = \log \frac{m_\beta(0,1)}{m_\beta(0,0)}  = \log m_\beta(0,1) - \log m_\beta(0,0)
\end{equation*}

With $m_\beta=\frac{1}{1+e}$, we have: $(\log m_\beta)^\prime = \frac{m_\beta^\prime}{m_\beta} = \frac{-e^\prime}{(1+e)^2} \times (1+e) = \frac{-e^\prime}{1+e}$

where $e_{01} = \exp(-\beta_0 - \beta_2)$ and $e_{00} = \exp(-\beta_0)$.

\begin{align*}
  \frac{\partial \log RR_{A_2 \mid A_1 = 0}}{\partial \beta_0} =& \frac{-(-e_{01})}{1 + e_{01}} - \frac{-(-e_{00})}{1 + e_{00}} \\
  =& \frac{1 + e_{01} - 1}{1 + e_{01}} - \frac{1 + e_{00} - 1}{1 + e_{00}} \\
  =& \left[1- m_\beta(0,1)\right] - \left[1 - m_\beta(0,0)\right] = m_\beta(0,0) - m_\beta(0,1)
\end{align*}

\begin{equation*}
  \frac{\partial \log RR_{A_2 \mid A_1 = 0}}{\partial \beta_1} =\frac{\partial \log RR_{A_2 \mid A_1 = 0}}{\partial \beta_3} = 0
\end{equation*}

\begin{align*}
  \frac{\partial \log RR_{A_2 \mid A_1 = 0}}{\partial \beta_2} =& \frac{-(-e_{01})}{1 + e_{01}} - 0 \\
  =& \frac{1 + e_{01} - 1}{1 + e_{01}} = 1- m_\beta(0,1)
\end{align*}

\begin{equation*}
  \frac{\partial \log RR_{A_2 \mid A_1 = 0}}{\partial \beta} = \begin{pmatrix} 
    m_\beta(0,0) - m_\beta(0,1) \\
    0 \\
    1- m_\beta(0,1) \\
    0
    \end{pmatrix} = \Delta
\end{equation*}

The variance of $\log RR_{A_2 \mid A_1 = 0}$ can then be calculated by:
\begin{equation*}
  var\left( \log RR_{A_2 \mid A_1 = 0}\right) = \Delta^T \times \frac{var(IC)}{n} \times \Delta
\end{equation*}

<!-- ######################################################################## -->
\newpage
## 4.4) Relative risk for the effect of $A_2$, setting $A_1=1$
\begin{equation*}
  \log RR_{A_2 \mid A_1 = 1} = \log \frac{m_\beta(1,1)}{m_\beta(1,0)}  = \log m_\beta(1,1) - \log m_\beta(1,0)
\end{equation*}

With $m_\beta=\frac{1}{1+e}$, we have: $(\log m_\beta)^\prime = \frac{m_\beta^\prime}{m_\beta} = \frac{-e^\prime}{(1+e)^2} \times (1+e) = \frac{-e^\prime}{1+e}$

where $e_{10} = \exp(-\beta_0 - \beta_1)$ and $e_{11} = \exp(-\beta_0- \beta_1 - \beta_2 - \beta_3)$.

\begin{align*}
  \frac{\partial \log RR_{A_2 \mid A_1 = 1}}{\partial \beta_0} =& \frac{-(-e_{11})}{1 + e_{11}} - \frac{-(-e_{10})}{1 + e_{10}} \\
  =& \frac{1 + e_{11} - 1}{1 + e_{11}} - \frac{1 + e_{10} - 1}{1 + e_{10}} \\
  =& \left[1- m_\beta(1,1)\right] - \left[1 - m_\beta(1,0)\right] = m_\beta(1,0) - m_\beta(1,1)
\end{align*}

\begin{align*}
  \frac{\partial \log RR_{A_2 \mid A_1 = 1}}{\partial \beta_1} =& \frac{1 + e_{11} - 1}{1 + e_{11}} - \frac{1 + e_{10} - 1}{1 + e_{10}} \\
  =& \left[1- m_\beta(1,1)\right] - \left[1 - m_\beta(1,0)\right] = m_\beta(1,0) - m_\beta(1,1)
\end{align*}

\begin{align*}
  \frac{\partial \log RR_{A_2 \mid A_1 = 1}}{\partial \beta_2} =& \frac{-(-e_{11})}{1 + e_{11}} - 0 \\
  =& \frac{1 + e_{11} - 1}{1 + e_{11}} = 1- m_\beta(1,1)
\end{align*}

\begin{align*}
  \frac{\partial \log RR_{A_2 \mid A_1 = 1}}{\partial \beta_3} =& \frac{-(-e_{11})}{1 + e_{11}} - 0 \\
  =& \frac{1 + e_{11} - 1}{1 + e_{11}} = 1- m_\beta(1,1)
\end{align*}

\begin{equation*}
  \frac{\partial \log RR_{A_2 \mid A_1 = 1}}{\partial \beta} = \begin{pmatrix} 
    m_\beta(1,0) - m_\beta(1,1) \\
    m_\beta(1,0) - m_\beta(1,1) \\
    1- m_\beta(1,1) \\
    1- m_\beta(1,1)
    \end{pmatrix} = \Delta
\end{equation*}

The variance of $\log RR_{A_2 \mid A_1 = 1}$ can then be calculated by:
\begin{equation*}
  var\left( \log RR_{A_2 \mid A_1 = 1}\right) = \Delta^T \times \frac{var(IC)}{n} \times \Delta
\end{equation*}


<!-- ######################################################################## -->
\newpage
# 5) Standard errors of interaction effects
## 5.1) Additive interaction
The additive interaction is defined by:
\begin{align*}
  \text{a.INT} =& m_\beta(1,1) - m_\beta(0,0) - \left[ \left( m_\beta(1,0) - m_\beta(0,0) \right) + \left( m_\beta(0,1) - m_\beta(0,0) \right)\right] \\
   =& m_\beta(1,1) - m_\beta(1,0) - m_\beta(0,1) + m_\beta(0,0)
\end{align*}

where
\begin{align*}
  m_\beta(1,1) =& \frac{1}{1 + e_{11}} \quad \text{ and } \quad e_{11} = \exp(-\beta_0 - \beta_1 - \beta_2 - \beta_3) \\
  m_\beta(1,0) =& \frac{1}{1 + e_{10}} \quad \text{ and } \quad e_{10} = \exp(-\beta_0 - \beta_1) \\
  m_\beta(0,1) =& \frac{1}{1 + e_{01}} \quad \text{ and } \quad e_{01} = \exp(-\beta_0 - \beta_2) \\
  m_\beta(0,0) =& \frac{1}{1 + e_{00}} \quad \text{ and } \quad e_{00} = \exp(-\beta_0)
\end{align*}

\begin{equation*}
\frac{\partial \text{a.INT}}{\partial \beta}  = \frac{-e_{11}^\prime}{(1 + e_{11})^2} - \frac{-e_{10}^\prime}{(1 + e_{10})^2} - \frac{-e_{01}^\prime}{(1+ e_{01})^2} + \frac{-e_{00}^\prime}{(1+e_{00})^2}
\end{equation*}

\begin{align*}
\frac{\partial \text{a.INT}}{\partial \beta_0}  =& \left(1-m_\beta(1,1)\right)m_\beta(1,1) - \left(1-m_\beta(1,0)\right)m_\beta(1,0) - \left(1-m_\beta(0,1)\right)m_\beta(0,1) + \left(1-m_\beta(0,0)\right)m_\beta(0,0) \\
\frac{\partial \text{a.INT}}{\partial \beta_1}  =& \left(1-m_\beta(1,1)\right)m_\beta(1,1) - \left(1-m_\beta(1,0)\right)m_\beta(1,0) \\
\frac{\partial \text{a.INT}}{\partial \beta_2}  =& \left(1-m_\beta(1,1)\right)m_\beta(1,1) - \left(1-m_\beta(0,1)\right)m_\beta(0,1) \\
\frac{\partial \text{a.INT}}{\partial \beta_3}  =& \left(1-m_\beta(1,1)\right)m_\beta(1,1) 
\end{align*}

\begin{equation*} \scriptsize
\frac{\partial \text{a.INT}}{\partial \beta}  = \begin{pmatrix} 
\left(1-m_\beta(1,1)\right)m_\beta(1,1) - \left(1-m_\beta(1,0)\right)m_\beta(1,0) - \left(1-m_\beta(0,1)\right)m_\beta(0,1) + \left(1-m_\beta(0,0)\right)m_\beta(0,0) \\
\left(1-m_\beta(1,1)\right)m_\beta(1,1) - \left(1-m_\beta(1,0)\right)m_\beta(1,0) \\
\left(1-m_\beta(1,1)\right)m_\beta(1,1) - \left(1-m_\beta(0,1)\right)m_\beta(0,1) \\
\left(1-m_\beta(1,1)\right)m_\beta(1,1) 
\end{pmatrix} 
\end{equation*}

The variance of $\text{a.INT}$ can then be calculated by:
\begin{equation*}
  var(\text{a.INT} ) = \left( \frac{\partial \text{a.INT}}{\partial \beta}\right)^T \times \frac{var(IC)}{n} \times \left( \frac{\partial \text{a.INT}}{\partial \beta}\right)
\end{equation*}


<!-- ######################################################################## -->
\newpage
## 5.2) Multiplicative interaction
The multiplicative interaction is defined by:
\begin{align*}
  \text{m.INT} =& \frac{m_\beta(1,1) \times m_\beta(0,0)}{m_\beta(1,0) \times m_\beta(0,1)} \\
   \log \text{m.INT} =& \log m_\beta(1,1) - \log m_\beta(1,0) -  \log m_\beta(0,1) + \log m_\beta(0,0)
\end{align*}

with $\frac{\partial}{\partial \beta} \log m_\beta = \frac{-e^\prime}{1+e}$, where
\begin{align*}
  e_{11} =& \exp(-\beta_0 - \beta_1 - \beta_2 - \beta_3) \\
  e_{10} =& \exp(-\beta_0 - \beta_1) \\
  e_{01} =& \exp(-\beta_0 - \beta_2) \\
  e_{00} =& \exp(-\beta_0)
\end{align*}

\begin{equation*}
\frac{\partial}{\partial \beta} \log \text{m.INT} = \frac{-e_{11}^\prime}{1 + e_{11}} - \frac{-e_{10}^\prime}{1 + e_{10}} - \frac{-e_{01}^\prime}{1+ e_{01}} + \frac{-e_{00}^\prime}{1+e_{00}}
\end{equation*}

\begin{align*}
\frac{\partial \log \text{m.INT}}{\partial \beta_0}  =& \frac{-(-e_{11})}{1 + e_{11}} - \frac{-(-e_{10})}{1 + e_{10}} - \frac{-(-e_{01})}{1+e_{01}} + \frac{-(-e_{00})}{1+e_{00}} \\
=& \left( 1 - m_\beta(1,1)\right) - \left( 1 - m_\beta(1,0)\right) - \left( 1 - m_\beta(0,1)\right) + \left( 1 - m_\beta(0,0)\right)\\
=& m_\beta(1,0) + m_\beta(0,1) - m_\beta(1,1) - m_\beta(0,0) \\
\frac{\partial \log \text{m.INT}}{\partial \beta_1}  =& \left(1-m_\beta(1,1)\right) - \left(1-m_\beta(1,0)\right) \\
=& m_\beta(1,0) - m_\beta(1,1) \\
\frac{\partial \log \text{m.INT}}{\partial \beta_2}  =& \left(1-m_\beta(1,1)\right) - \left(1-m_\beta(0,1)\right) \\
=& m_\beta(0,1) - m_\beta(1,1) \\
\frac{\partial \log \text{m.INT}}{\partial \beta_3}  =& \left(1-m_\beta(1,1)\right)
\end{align*}

\begin{equation*} \scriptsize
\frac{\partial \log \text{m.INT}}{\partial \beta}  = \begin{pmatrix} 
m_\beta(1,0) + m_\beta(0,1) - m_\beta(1,1) - m_\beta(0,0) \\
m_\beta(1,0) - m_\beta(1,1) \\
m_\beta(0,1) - m_\beta(1,1) \\
1-m_\beta(1,1)
\end{pmatrix} 
\end{equation*}

The variance of $\log \text{m.INT}$ can then be calculated by:
\begin{equation*}
  var(\log \text{m.INT} ) = \left( \frac{\partial \log \text{m.INT}}{\partial \beta}\right)^T \times \frac{var(IC)}{n} \times \left( \frac{\partial \log \text{m.INT}}{\partial \beta}\right)
\end{equation*}

<!-- ######################################################################## -->
\newpage
## 5.3) RERI
The RERI is defined by:
\begin{align*}
  \text{RERI} =& \frac{m_\beta(1,1) - m_\beta(1,0) - m_\beta(0,1) + m_\beta(0,0)}{m_\beta(0,0)} \\
   \log \text{RERI} =& \log \left[m_\beta(1,1) - m_\beta(1,0) - m_\beta(0,1) + m_\beta(0,0)\right] - \log m_\beta(0,0)
\end{align*}

denoting
\begin{align*}
  e_{11} =& \exp(-\beta_0 - \beta_1 - \beta_2 - \beta_3) \\
  e_{10} =& \exp(-\beta_0 - \beta_1) \\
  e_{01} =& \exp(-\beta_0 - \beta_2) \\
  e_{00} =& \exp(-\beta_0)
\end{align*}

\begin{equation*}
  \frac{\partial}{\partial \beta} \log m_\beta(0,0) = \frac{m_\beta(0,0)^\prime}{m_\beta(0,0)} = \frac{-e_{00}^\prime}{(1+e_{00})^2} (1 + e_{00}) = \frac{-e_{00}^\prime}{1+e_{00}}
\end{equation*}

\begin{equation*}
  \frac{\partial}{\partial \beta} \log \left[m_\beta(1,1) - m_\beta(1,0) - m_\beta(0,1) + m_\beta(0,0)\right] = \frac{m_\beta(1,1)^\prime - m_\beta(1,0)^\prime - m_\beta(0,1)^\prime + m_\beta(0,0)^\prime}{m_\beta(1,1)  - m_\beta(1,0) - m_\beta(0,1) + m_\beta(0,0)}
\end{equation*}

\begin{multline*}
\frac{\partial \log \text{RERI}}{\partial \beta_0} = \frac{\left[1 - m_\beta(1,1)\right]m_\beta(1,1) - \left[1 - m_\beta(1,0)\right]m_\beta(1,0) - \left[1 - m_\beta(0,1)\right]m_\beta(0,1) + \left[1 - m_\beta(0,0)\right]m_\beta(0,0)}{m_\beta(1,1) - m_\beta(1,0) - m_\beta(0,1) + m_\beta(0,0)}\\
- \left[1 - m_\beta(0,0)\right] 
\end{multline*}

\begin{align*}
  \frac{\partial \log \text{RERI}}{\partial \beta_1} =& \frac{\left[1 - m_\beta(1,1)\right]m_\beta(1,1) - \left[1 - m_\beta(1,0) \right]m_\beta(1,0)}{m_\beta(1,1) - m_\beta(1,0) - m_\beta(0,1) + m_\beta(0,0)} \\
  \frac{\partial \log \text{RERI}}{\partial \beta_2} =& \frac{\left[1 - m_\beta(1,1)\right]m_\beta(1,1) - \left[1 - m_\beta(0,1) \right]m_\beta(0,1)}{m_\beta(1,1) - m_\beta(1,0) - m_\beta(0,1) + m_\beta(0,0)} \\
  \frac{\partial \log \text{RERI}}{\partial \beta_3} =& \frac{\left[1 - m_\beta(1,1)\right]m_\beta(1,1)}{m_\beta(1,1) - m_\beta(1,0) - m_\beta(0,1) + m_\beta(0,0)}
\end{align*}


The variance of $\log \text{RERI}$ can then be calculated by:
\begin{equation*}
  var(\log \text{RERI} ) = \left( \frac{\partial \log \text{RERI}}{\partial \beta}\right)^T \times \frac{var(IC)}{n} \times \left( \frac{\partial \log \text{RERI}}{\partial \beta}\right)
\end{equation*}
